### PR TITLE
Added new game Sudoku with GUI

### PR DESCRIPTION
**Pull request by Yarlin16**
## Description of changes:
I have added a new game : Sudoku with GUI under #KWoC 2023.
The project is done using pygame for GUI. Also, after the user closes the window after his/her attempt, the program prints all other possible answers for the same sudoku puzzle in the terminal.
Also, I have updated the README file for the project with screenshots.

## Issue ticket number:
#77 

## Screenshots of the project output:
Screenshot 2023-12-21 210632
Screenshot 2023-12-21 210721
Screenshot 2023-12-21 210827
Screenshot 2023-12-21 210852

## Checklist:
- [x] I have performed a self-review of my code
- [x] If it is a new project, I have done thorough tests.
- [x] Have you updated the `README.md` file of the repository and added the name of the project in it?
- [x] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Comment by shrey141102** [comment]
Looks good but i still dont understand why so many files are changed

**Comment by shrey141102** [comment]
image

**Comment by Yarlin16** [comment]
That was because I have already opened a PR before this PR in which I have updated the README files for other projects. 

Those changes still didn't get merged so it has shown that they required merging too.

**Comment by Yarlin16** [comment]
If you could merge the pull request #79 before this PR, then the merge conflicts won't be there I guess.

**Comment by shrey141102** [comment]
> If you could merge the pull request #79 before this PR, then the merge conflicts won't be there I guess.

The other Pr also has few unrelated changes

**Comment by shrey141102** [comment]
Just add a fresh PR with all the changes that you want to submit. It would be easier to check then. Thanks for understanding

**Comment by Yarlin16** [comment]
Yep, then I'll open just one pr for all the changes. 👍

**Comment by shrey141102** [comment]
> Yep, then I'll open just one pr for all the changes. 👍

That would be great

**Pull request closed without merging**
