### PR TITLE
fix : Readme.md

### PR DESCRIPTION
**Pull request by shubha987**
## Issue #38 

I am working on the changes and please keep this pull request open i want to see the changes on github.

### CODE REVIEW

**Comment by shubha987** [comment]
Its still in working phase though

**Comment by shrey141102** [comment]
its okay bro

**Comment by shubha987** [comment]
and the website is still in progress and other readme updates are with it please see the changes

**Comment by shrey141102** [comment]
> and the website is still in progress and other readme updates are with it please see the changes

all good

**Pull request merged**
