### PR TITLE
Smoother gameplay (FPS boosted) and Recording Scores

### PR DESCRIPTION
**Pull request by ayushlostvolts**
## Describe your changes (Mandatory) 
Improved the FPS and the overall performance of the game 
Added an excel sheet to keep score of all players that plays the game
(for each player their consecutive scores gets stored in consecutive columns)
## Screenshots of your project output, whatever you have added. (Mandatory)
image_2024-01-05_231223945

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a new project, I have done thorough tests.
- [ ] Have you updated the README file of the repository and added the name of the project in it?
- [ ] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Comment by shrey141102** [comment]
@ayushlostvolts conflicts are there
Please resolve those

**Comment by ayushlostvolts** [comment]
I have resolved the conflict. Please check @shrey141102

**Comment by ayushlostvolts** [comment]
@shrey141102 Please let me know if this works.

**Comment by shrey141102** [comment]
image
Hey, everything else is good but why are there changes in other files??

**Comment by shrey141102** [comment]
Also, I cant see any excel file

**Pull request closed without merging**
