### PR TITLE
ascii retry

### PR DESCRIPTION
**Pull request by Tanmay0215**
## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a new project, I have done thorough tests.
- [ ] Have you updated the README file of the repository and added the name of the project in it?
- [ ] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Comment by shrey141102** [comment]
image
 brooo....

**Comment by shrey141102** [comment]
i removed the other files but i cannot remove the .pdf file

**Comment by Tanmay0215** [comment]
how can I do pls suggest
whenever i create new pr all commit gets in the pr

**Comment by shrey141102** [comment]
> how can I do pls suggest whenever i create new pr all commit gets in the pr

Hey man, @Tanmay0215 I can't help you out like this 😢 
Come in discord voice channel, there we will try to fix this

**Pull request merged**
