### PR TITLE
Addgrocery

### PR DESCRIPTION
**Pull request by ogsahil**
## Describe your changes (Mandatory) 
i have added a grocery program 
it contains two files-
one for storing the products in the store(AvailableProduct.txt)
another one for performing all the major operation to execute the code.

## Issue ticket number and link (Mandatory)
118

## Screenshots of your project output, whatever you have added. (Mandatory)
ss1
ss2

## Checklist before requesting a review
- [✅] I have performed a self-review of my code
- [✅] If it is a new project, I have done thorough tests.
- [❎] Have you updated the README file of the repository and added the name of the project in it?
- [❎] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Comment by shrey141102** [comment]
check for conflicts

**Comment by shrey141102** [comment]
@ogsahil

**Comment by ogsahil** [comment]
Done!

**Comment by shrey141102** [comment]
good job!

**Pull request merged**
