### PR TITLE
Type Tester

### PR DESCRIPTION
**Pull request by kausthub-kannan**
## Describe your changes (Mandatory) 
Added Type Tester

## Issue ticket number and link (Mandatory)
#21 

## Screenshots of your project output, whatever you have added. (Mandatory)
<a href="https://ibb.co/1Jp2DPD">Screenshot-20231212-233736</a>

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a new project, I have done thorough tests.
- [x] Have you updated the README file of the repository and added the name of the project in it?
- [x] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Comment by kausthub-kannan** [comment]
@shrey141102 I have added the projects with required docs

**Comment by shrey141102** [comment]
please add screenshots. that helps in evaluating your submission
@kausthub-kannan

**Comment by kausthub-kannan** [comment]
> please add screenshots. that helps in evaluating your submission @kausthub-kannan

@shrey141102 I have added screenshots in README.md file within the project directory  
  
<a href="https://ibb.co/Dz5JMNV">Screenshot-20231212-185753</a>

**Comment by kausthub-kannan** [comment]
@shrey141102 Should I update anything?

**Pull request merged**
