### PR TITLE
colored print

### PR DESCRIPTION
**Pull request by Tanmay0215**
## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a new project, I have done thorough tests.
- [ ] Have you updated the README file of the repository and added the name of the project in it?
- [ ] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Review by shrey141102 — COMMENTED** [review]
Please add all files in a folder

**Review by shrey141102 — CHANGES_REQUESTED** [review]
please add files in a folder

**Comment by Tanmay0215** [comment]
could you guide how to do it I have it 2-3 times and it always comes like this

**Comment by shrey141102** [comment]
bro ask for help in discord community

Its simple only, if you redo the PR, just while pushing all code files, first put them in a folder

**Pull request closed without merging**
