### PR TITLE
feat : website in progress

### PR DESCRIPTION
**Pull request by shubha987**
## Issue #1 

Please suggest me changes I have to go to according ly

### CODE REVIEW

**Comment by shrey141102** [comment]
damn, lot of work you've done

Any screenshots/demo?

**Comment by shrey141102** [comment]
And keep the html css files and all in the repository (outside, not inside any folder) so that we can depoly it in github pages

**Comment by shubha987** [comment]
basically i want to redecorate your website like this project it is one of my project so please give me the required suggestion so that we can proceed with it as date is approaching for kwoc end

**Comment by shubha987** [comment]
> And keep the html css files and all in the repository (outside, not inside any folder) so that we can depoly it in github pages

well its not a static webpage so we cannot deploy it on github

**Comment by shubha987** [comment]
> damn, lot of work you've done
> 
> Any screenshots/demo?

wait i am sending how it will look as it contain backend we have to make it as localhost or any paid hosting server like hostinger or aws . i dont have any idea of hosting in server though.

**Comment by shubha987** [comment]
Screenshot 2023-12-12 225917
the images and carousal can be changed.

**Comment by shrey141102** [comment]
> > damn, lot of work you've done
> > Any screenshots/demo?
> 
> wait i am sending how it will look as it contain backend we have to make it as localhost or any paid hosting server like hostinger or aws . i dont have any idea of hosting in server though.

do localhost only

bro send in discord

**Comment by shrey141102** [comment]
> > And keep the html css files and all in the repository (outside, not inside any folder) so that we can depoly it in github pages
> 
> well its not a static webpage so we cannot deploy it on github

ahh

**Comment by shrey141102** [comment]
> basically i want to redecorate your website like this project it is one of my project so please give me the required suggestion so that we can proceed with it as date is approaching for kwoc end

ig discuss in discord everyone can suggest there. It's for everyone 😅

**Comment by shrey141102** [comment]
> Screenshot 2023-12-12 225917 the images and carousal can be changed.

looks good enough

**Comment by shubha987** [comment]
> > > damn, lot of work you've done
> > > Any screenshots/demo?
> > 
> > 
> > wait i am sending how it will look as it contain backend we have to make it as localhost or any paid hosting server like hostinger or aws . i dont have any idea of hosting in server though.
> 
> do localhost only
> 
> bro send in discord

ok wait i am sending but images and all the links have to be updated i have just created a demo

**Comment by shrey141102** [comment]
> > > > damn, lot of work you've done
> > > > Any screenshots/demo?
> > > 
> > > 
> > > wait i am sending how it will look as it contain backend we have to make it as localhost or any paid hosting server like hostinger or aws . i dont have any idea of hosting in server though.
> > 
> > 
> > do localhost only
> > bro send in discord
> 
> ok wait i am sending but images and all the links have to be updated i have just created a demo

yeah, no hurry bro

**Pull request closed without merging**
