### PR TITLE
 feat : GUI game for Guess-the-number

### PR DESCRIPTION
**Pull request by shubha987**
## Issue #55 

Screenshot 2023-12-14 004315

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a new project, I have done thorough tests.

### CODE REVIEW

**Comment by shubha987** [comment]
@shrey141102  check it out

**Comment by shrey141102** [comment]
@shubha987 reove the pycache files. Else everything looks good

**Comment by shrey141102** [comment]
image

**Comment by shubha987** [comment]
i guess i have solved it please check it out @shrey141102

**Comment by shrey141102** [comment]
image
still there..

**Comment by shubha987** [comment]
ok wait

**Comment by shubha987** [comment]
ok check it now ... is it still there ? @shrey141102

**Pull request merged**
