### PR TITLE
feat : Website for the repo

### PR DESCRIPTION
**Pull request by shubha987**
## Issue #1 

Screenshot 2024-01-07 202240
Screenshot 2024-01-07 202251

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a new project, I have done thorough tests.
- [x] Have you updated the README file of the repository and added the name of the project in it?
- [x] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?

### CODE REVIEW

**Comment by shubha987** [comment]
well i have to add some pictures and functionality but the template is overall ready and as the bootstrap is used so it is responsive by deafult

**Comment by shubha987** [comment]
check it out.... @shrey141102

**Comment by shrey141102** [comment]
Looks nice

**Comment by shubha987** [comment]
okay then you can merge it and deploy it in github pages

**Pull request merged**
